vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
       products:
           uri_prefix: /images/upload/paints
           upload_destination: '%kernel.project_dir%/public/images/upload/paints'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
