-- phpMyAdmin SQL Dump
-- version 5.1.3
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost
-- Généré le : lun. 04 juil. 2022 à 12:34
-- Version du serveur : 5.7.33
-- Version de PHP : 8.1.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `qualideco`
--

-- --------------------------------------------------------

--
-- Structure de la table `category`
--

CREATE TABLE `category` (
  `id` int(11) NOT NULL,
  `name` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `category`
--

INSERT INTO `category` (`id`, `name`) VALUES
(8, 'Primaire/Impression'),
(9, 'Finitions'),
(10, 'Decoration'),
(11, 'Façade'),
(12, 'Bois'),
(13, 'Sols'),
(14, 'Métaux');

-- --------------------------------------------------------

--
-- Structure de la table `doctrine_migration_versions`
--

CREATE TABLE `doctrine_migration_versions` (
  `version` varchar(191) COLLATE utf8_unicode_ci NOT NULL,
  `executed_at` datetime DEFAULT NULL,
  `execution_time` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Structure de la table `messenger_messages`
--

CREATE TABLE `messenger_messages` (
  `id` bigint(20) NOT NULL,
  `body` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `headers` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue_name` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL,
  `available_at` datetime NOT NULL,
  `delivered_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Structure de la table `paints`
--

CREATE TABLE `paints` (
  `id` int(11) NOT NULL,
  `title` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cover` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `destination` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `features` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `price` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `paints`
--

INSERT INTO `paints` (`id`, `title`, `cover`, `destination`, `features`, `description`, `price`) VALUES
(1, 'Capitole aqua primaire universel', 'https://www.peintures-innova.fr/thumbs/peintures/primaire-impression/capitole-aqua-primaire-universel/innova-capitole-aqua-primai-510x574.png', 'Intérieur/Extérieur.\r\nTravaux neufs et de rénovation.\r\nSur tous supports usuels du bâtiment : bois et dérivés, métaux ferreux et non ferreux, plâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes, PVC', 'Excellent pouvoir opacifiant.\r\nAspect tendu.\r\nBloque les remontées de tanins.\r\nRecouvrable dans la journée.\r\nContient un inhibiteur de corrosion et un agent anti-tannique.\r\nBloque et durcit les fonds.\r\nGrande dureté du film', '\r\n\r\nDensité : 1.38\r\nRendement : 10 - 12 m2/L\r\nBase : BLANC\r\nConditionnement : 1L, 3L, 12L\r\n\r\n', 35),
(3, 'Capitole classic impression* (Novapret 20) ', 'https://www.peintures-innova.fr/thumbs/peintures/primaire-impression/capitole-classic-impression/innova-capitole-classic-imp-510x605.png', 'Intérieur/Extérieur.\r\nTravaux neufs et de rénovation.\r\nParticulièrement adaptée sur boiseries en sous-couche de laques glycéro.\r\nPlâtres et dérivés, anciennes peintures adhérentes, bois et dérivés à l\'intérieur et à l\'extérieur', 'Bon pouvoir opacifiant.\r\nForte action pénétrante, microporeuse.\r\nFacilité d\'application, garnissante.\r\nBloque et durcit les fonds.\r\nLongue en huile, excellente durabilité', 'Densité : 1.45\r\nRendement : 10 - 12 m2/L\r\nBase : BLANC\r\nConditionnement : 0.75L, 3L, 15L\r\n\r\n', 40),
(4, 'Calanque impression ', 'https://www.peintures-innova.fr/thumbs/peintures/primaire-impression/calanque-impression/innova-calanque-impression-510x701.png', '\r\nIntérieur/ Extérieur.\r\nTravaux neufs et de rénovation.\r\nRecouvrable par toutes finitions acryliques.\r\nPlâtres et dérivés, anciennes peintures adhérentes, bois et dérivés à l\'intérieur.\r\n\r\n', '\r\n\r\n    Bon pouvoir opacifiant, masque taches et embus.\r\n    Prêt à l\'emploi.\r\n    Recouvrable dans la journée.\r\n    Bloque et durcit les fonds.\r\n    NF environnement - Taux C.O.V. < 5g/l\r\n\r\n', '\r\n\r\nDensité : 1.54\r\nRendement : 10 - 12 m2/L\r\nBase : BLANC\r\nConditionnement : 1L, 3L, 15L\r\n\r\n', 45),
(5, 'Esterel impression ', 'https://www.peintures-innova.fr/thumbs/peintures/primaire-impression/esterel-impression/innova-esterel-impression-510x701.png', 'Intérieur/Extérieur.\r\nTravaux neufs et de rénovation.\r\nPour tous les supports absorbants usuels du bâtiment.\r\nParticulièrement sur Placoplatre.\r\nPlâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes', '\r\n\r\n\r\n    Bon pouvoir opacifiant.\r\n    Prêt à l\'emploi.\r\n    Ponçable et recouvrable dans la journée.\r\n    Régule l\'absorption des supports.\r\n    NF Environnement - Taux C.O.V < 5g/l\r\n\r\n\r\n    \r\n   ', '\r\n\r\nDensité : 1.54\r\nRendement : 8 - 10 m2/L\r\nBase : BLANC\r\nConditionnement : 3L, 15L\r\n\r\n', 49),
(6, 'Novalis impression ', 'https://www.peintures-innova.fr/thumbs/peintures/primaire-impression/novalis-impression/innova-novalis-render-impression_bd-510x701.png', 'Intérieur / Extérieur\r\nTravaux neufs et de rénovation\r\nRecouvrable par toutes finitions acryliques\r\nPlâtre et dérivés, anciennes peintures adhérentes, bois et dérivés à l\'intérieur', '\r\n\r\n    Bon pouvoir couvrant\r\n    Prêt à l\'emploi\r\n    Recouvrable dans la journée\r\n    Bloque et durcit les fonds\r\n    Taux de C.O.V <5g/L\r\n\r\n', '\r\n\r\nDensité : 1,54\r\nRendement : 10-12m²/L\r\nBase : BLANC\r\nConditionnement : 1L, 3L, 15L\r\n\r\n', 55),
(7, 'Novabat Impression ', 'https://www.peintures-innova.fr/thumbs/peintures/primaire-impression/novabat-sous-couche/innova-novabat-ssc_detour-510x565.png', '\r\n\r\n    Intérieur\r\n    Travaux neufs et de rénovation\r\n    Pour tous les supports absorbants usuels du bâtiment\r\n    Plâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes\r\n\r\n', '\r\n\r\n    Bon pouvoir couvrant\r\n    Prêt à l\'emploi\r\n    Régule l\'absorption des supports\r\n    Taux de C.O.V <5g/L\r\n\r\n', '\r\n\r\nDensité : 1,59\r\nRendement : 10-12m²/L\r\nBase : BLANC\r\nConditionnement : 15L\r\n\r\n', 43),
(8, 'Novaprim ', '\r\nhttps://www.peintures-innova.fr/thumbs/peintures/primaire-impression/novaprim/novaprim-510x701.jpg\r\n', '\r\n\r\n    Intérieur\r\n    Travaux neufs et de rénovation\r\n    Particulièrement adaptée sur boiseries en sous-couche de laques glycéro\r\n    Plâtres et dérivés, bois et dérivés, anciennes peintures adhérentes, bois et dérivés intérieur\r\n\r\n', '\r\n\r\n    Bon pouvoir opacifiant\r\n    Forte action pénétrante, microporeuse\r\n    Facilité d\'application\r\n    Garnissante\r\n    Bloque et durcit les fonds\r\n\r\n', '\r\n\r\nDensité : 1,28\r\nRendement : 10-12m²/L\r\nBase :BLANC\r\nConditionnement : 15L\r\n\r\n', 54),
(36, 'Capitole aqua brillant* (Laque brillante aqua de capitole)', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/brillante/capitole-aqua-brillant/innova-capitole-aqua-brilla-510x574.png', 'Intérieur / Extérieur\r\nTravaux neufs et de rénovation\r\nApplication au rouleau laqueur ou à la brosse\r\nPlâtres et dérivés, bétons et dérivés, bois et dérivés, anciennes peintures adhérentes \r\nSpécialement adaptée pour les boiseries extérieures', ' \r\n\r\n \r\n\r\nBon pouvoir opacifiant\r\nAspect brillant tendu\r\nExcellente dureté, lessivable, facile d\'entretien\r\nSéchage hors poussières 30 mn\r\nExcellente résistance aux U.V\r\nSans odeur\r\nBrilance à 80° : 70 U.B\r\n\r\n\r\n\r\n   \r\n\r\n \r\n\r\n', '\r\n\r\nDensité : 1.29\r\nRendement : 12 - 14 m2/L\r\nBase :BLANC - INCOLORE\r\nConditionnement : 1L, 3L, 12L\r\n\r\n', 60),
(37, 'Capitole premium brillant* (Laque brillante de capitole) ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/brillante/capitole-premium-brillant/innova-capitole-premium-bri-510x574.png', '\r\nIntérieur / Extérieur\r\nTravaux neufs et de rénovation\r\nApplication au rouleau laqueur ou à la brosse.\r\nPlâtres et dérivés, bétons et dérivés, bois et dérivés, anciennes peintures adhérentes \r\nSpécialement adaptée pour les boiseries extérieures', 'Excellent pouvoir garnissant et opacifiant\r\nAspect brillant tendu\r\nLessivable, facilité d\'entretien\r\nMicroporeuse. Longue en huile\r\nGrande facilité d\'application. Rendement élevé\r\nBonne résistance aux intempéries et aux U.V\r\nBrillance à 80° : > 80 U.B\r\n\r\n', '\r\n\r\nDensité : 1.21\r\nRendement : 14 - 16 m2/L\r\nBase :  BLANC - INCOLORE\r\nConditionnement : 0.75L, 3L\r\n\r\n', 48),
(38, 'Capitole aqua satin* (Laque satin aqua de capitole) ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/satinee/capitole-aqua-satin/innova-capitole-aqua-satin-510x574.png', 'Intérieur/Extérieur\r\nTravaux neufs et de rénovation\r\nApplication au rouleau laqueur\r\nPlâtres et dérivés, bétons et dérivés, bois et dérivés, anciennes peintures      adhérentes\r\nSpécial boiseries intérieures\r\nSur CAPITOLE AQUA Primaire Universel\r\n\r\n', '    Bon pouvoir opacifiant\r\n    Aspect satin tendu\r\n    Excellente dureté, lessivable, facilité d’entretien\r\n    Séchage hors poussières 30mn\r\n    Excellente résistance aux U.V\r\n    Sans odeur\r\n    Brillance à 60° : 20 U.B (+/-2)\r\n\r\n', '\r\n\r\nDensité : 1.38\r\nRendement : 12 - 14 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 1L, 3L, 12L\r\n\r\n', 37),
(39, 'Capitole premium satin* (Laque satin de capitole) ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/satinee/capitole-premium-satin/innova-capitole-premium-sat-510x574.png', 'Intérieur/Extérieur.\r\nTravaux neufs et de rénovation.\r\nApplication au rouleau laqueur ou à la brosse.\r\nPlâtres et dérivés, bois et dérivés, anciennes peintures adhérentes.\r\nSpécialement adapté pour les boiseries extérieures', '    \r\n\r\n    Excellent pouvoir garnissant et opacifiant.\r\n    Aspect satin tendu.\r\n    Lessivable, facilité d’entretien.\r\n    Microporeuse.\r\n    Grande facilité d’application. Rendement élevé.\r\n    Brillance à 60° : 25 U.B (+/-2)\r\n\r\n\r\n\r\n    \r\n\r\n', '\r\n\r\nDensité : 1.43\r\nRendement : 14 - 16 m2/L\r\nBase : BLANC -INCOLORE\r\nConditionnement : 0.75L, 3L, 12L\r\n\r\n', 47),
(40, 'Calanque satin ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/satinee/calanque-satin/calanque-satin-510x608.png', '\r\n\r\n    Intérieur.\r\n    Travaux neufs et de rénovation.\r\n    Application au rouleau laqueur ou à la brosse.\r\n    Plâtres et dérivés, bois et dérivés, anciennes peintures adhérentes.\r\n\r\n', '\r\nBon pouvoir garnissant et opacifiant Finition satinée soyeuse, semi tendue Lessivable facile d’entretien Bonne blancheur très faible jaunissement à l’obscurité\r\nGrande facilité d’application. Rendement élevé\r\nSans odeur\r\nBrillance à 60° : 20 U.B (+/-2)\r', '\r\n\r\nDensité : 1.44\r\nRendement : 12 -14 m2\r\nBase : BLANC - INCOLORE\r\nConditionnement : 1L, 3L, 12L\r\n\r\n', 24),
(45, 'Capitole classic satin* (Novasatin HES) ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/satinee/capitole-classic-satin/capitole_classic_satin-510x559.png', '\r\n\r\nIntérieur / Extérieur.\r\nTravaux neufs et de rénovation.\r\nApplication au rouleau, brosse ou mécanisée.\r\nPlâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes.\r\nSur CAPITOLE CLASSIC Impression sur boiseries extérieures\r\n\r\n', '\r\n\r\n    Excellent pouvoir garnissant et opacifiant.\r\n    Finition satinée semi-tendue.\r\n    Lessivable, facile d’entretien.\r\n    Microporeuse.\r\n    Grande facilité d’application. Rendement élevé.\r\n    Brillance à 60° : 20 U.B\r\n\r\n\r\n   \r\n\r\n', '\r\n\r\nDensité : 1.45\r\nRendement : 12 - 14 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 3L, 15L\r\n\r\n', 28),
(46, 'Novalis satin ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/satinee/novalis-satin/innova-novalis-render-satin-510x701.png', '\r\n\r\n    Murs et plafonds intérieurs\r\n    Travaux neufs et de rénovation\r\n    Idéal pour la mise en peinture des cuisines et pièces humides\r\n    Plâtres et dérivés, bois et dérivés, anciennes peintures adhérentes\r\n\r\n', '\r\nExcellent pouvoir garnissant et opacifian Finition satin doux tenduLessivable, non lustrant, facile d\'entretien Grande blancheur, bel aspect tendu Grande facilité d\'application Temps ouvert important Sans odeur Rendement élevé Brillance à 60° : 15U.+/-2', '\r\n\r\nDensité : 1,36\r\nRendement : 12 - 14 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 1L, 3L, 15L\r\n\r\n', 52),
(47, 'Still \"classic\" satin* (novacryl satin) ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/satinee/still-classic-satin/still-classic-satin-510x559.png', 'Intérieur / Extérieur.\r\nTravaux neufs et de rénovation.\r\nApplication au rouleau, brosse ou mécanisée.\r\nPlâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes', 'Bon pouvoir garnissant et opacifiant\r\nFinition satinée pochée.\r\nLessivable, facilité d’entretien.\r\nGrande facilité d’application. Rendement élevé.\r\nBrillance à 60° : 35 U.B', '\r\n\r\nDensité : 1.32\r\nRendement : 12-14 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 1L, 3L, 15L\r\n\r\n', 27),
(48, 'Esterel satin ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/satinee/esterel-satin/innova-esterel-satin-510x701.png', 'Intérieur / Extérieur.\r\nTravaux neufs et de rénovation.\r\nApplication au rouleau, brosse ou mécanisée.\r\nPlâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes.\r\nSpécial toile de verre', '\r\n\r\n    Bon pouvoir garnissant et opacifiant.\r\n    Finition satinée pochée.\r\n    Lessivable, facile d’entretien.\r\n    Grande facilité d’application. Rendement élevé.\r\n    Brillance à 60° : 15 U.B\r\n\r\n', '\r\n\r\nDensité : 1.34\r\nRendement : 10 - 12 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 3L, 15L\r\n\r\n', 32),
(49, 'Novabat satin \r\n\r\n', '\r\nhttps://www.peintures-innova.fr/thumbs/peintures/finitions/satinee/novabat-satin/innova-novabat-satin_detour-510x565.png\r\n\r\n', '\r\n\r\n    Intérieur\r\n    Travaux neufs et de rénovation\r\n    Application au rouleau, brosse ou mécanisée\r\n    Plâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes\r\n\r\n\r\n    \r\n\r\n', '\r\n\r\n    Bon pouvoir garnissant et opacifiant\r\n    Finition satinée pochée\r\n    Lessivable, facile d\'entretien\r\n    Grande facilité d\'application\r\n    Brillance à 60° : 15 U.B\r\n\r\n', '\r\n\r\nDensité : 1,34\r\nRendement : 10-12m²/L\r\nBase : BLANC\r\nConditionnement : 15L\r\n\r\n', 36),
(50, 'Novagliss', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/satinee/novagliss/novagliss-510x559.png', ' Intérieur.\r\n Travaux neufs et de rénovation.\r\n Application au rouleau, brosse ou mécanisée.\r\n Plâtres et dérivés, bois et dérivés, anciennes peintures adhérentes\r\nsur CAPITOLE CLASSIC Impression sur boiseries extérieures', 'Bon pouvoir garnissant et opacifiant.\r\nFinition poché arrondi.\r\nLessivable, facilité d’entretien.\r\nMicroporeuse.\r\nGrande facilité d’application.\r\nBrillance à 60° : 20 U.B', '\r\n\r\nDensité : 1.37\r\nRendement : 10-12m²/L\r\nBase : BLANC\r\nConditionnement : 15L\r\n\r\n', 65),
(51, 'Calanque soie ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/soie/calanque-soie/calanque-soie-510x607.png', '\r\n\r\n    Intérieur.\r\n    Travaux neufs et de rénovation.\r\n    Application au rouleau laqueur ou à la brosse.\r\n    Plâtres et dérivés, bois et dérivés, anciennes peintures adhérentes.\r\n    Finition avec un bel aspect décoratif\r\n\r\n', '\r\n\r\n    Bon pouvoir garnissant et opacifiant.\r\n    Finition mate velours tendue + non lustrant.\r\n    Lessivable, facilité d’entretien.\r\n    Bonne blancheur.\r\n    Grande facilité d’application. Rendement élevé.\r\n    Sans odeur.\r\n    Brillance à 60° : 7 U.B', '\r\n\r\nDensité : 1.58\r\nRendement : 14 - 16 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 1L, 3L, 12L\r\n\r\n', 38),
(52, 'Capitole aqua velours* (Laque velours aqua de capitole) ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/velours/capitole-aqua-velours/innova-capitole-aqua-velour-510x574.png', ' Intérieur/Extérieur.\r\n Travaux neufs et de rénovation.\r\n Application au rouleau laqueur.\r\n Plâtres et dérivés, bétons et dérivés, bois et dérivés, anciennes peintures adhérentes\r\n\r\n', 'Finition mat velours, tendue.Bon pouvoir opacifiant.Excellente dureté, lessivable, facile d’entretien.Non lustrable.Séchage hors poussières 30mn.Excellente résistance aux U.V.Sans odeur.Brillance à 60° : 5 U.B\r\n\r\n\r\n\r\n', '\r\n\r\nDensité : 1.58\r\nRendement : 14 - 16 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 1L, 3L, 12L\r\n\r\n', 42),
(53, 'Calanque velours', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/velours/calanque-velours/calanque-velours-510x608.png', '\r\n\r\n    Intérieur.\r\n    Finition avec un bel aspect décoratif.\r\n    Travaux neufs et de rénovation.\r\n    Application au rouleau laqueur ou à la brosse.\r\n    Plâtres et dérivés, bois et dérivés, anciennes peintures adhérentes.\r\n\r\n', '\r\n\r\n    Finition mate velours tendu.\r\n    Bon pouvoir garnissant et opacifiant.\r\n    Lavable, facile d’entretien.\r\n    Excellente blancheur.\r\n    Grande facilité d’application. Rendement élevé.\r\n    Brillance à 60° : 3-4 U.B\r\n\r\n', '\r\n\r\nDensité : 1.60\r\nRendement : 14 - 16 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 1L, 3L, 12L\r\n\r\n', 48),
(54, 'Calanque Nov Velours ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/velours/calanque-nov-velours/calanque-nov_velours-15l050-510x701.png', 'La gamme CALANQUE est particulièrement recommandée pour peindre dans les locaux publics et les locaux à exigences d’hygiène élevées tels que les hôpitaux, écoles, maisons de retraite', 'Finition haute qualité Aspect mat velours ou satin soyeux Pouvoir couvrant et rendement élevé Masque les légères imperfections du support Résistance au lustrage (Classe 1) & LESSIVABLE Brillance à 60° : 5 U.B\r\n\r\n\r\n\r\n', '\r\n\r\nDensité : 1.52\r\nRendement : 12 à 14 m²/L selon la porosité du support\r\nBase : BLANC - INCOLORE\r\nConditionnement : 1L, 3L, 15L\r\n\r\n', 39),
(55, 'Novalis velours ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/velours/novalis-velours/innova-novalis-render-velours-510x701.png', '\r\n\r\n    Intérieur\r\n    Travaux neufs et de rénovation\r\n    Application au rouleau, brosse ou mécanisée\r\n    Plâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes\r\n\r\n', 'Finition veloutée tendue Non lustrant Lavable et lessivable  Facile d\'entretien Temps de reprise élevé Pouvoir opacifiant important Grande blancheur Brillance à 60) : 5/6 U.B\r\n\r\n', '\r\n\r\nDensité : 1,35\r\nRendement : 12 - 14 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 1L, 3L, 15L\r\n\r\n', 48),
(59, 'Esterel velours ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/velours/esterel-velours/innova-esterel-velours-510x701.png', 'Intérieur.\r\nTravaux neufs et de rénovation.\r\nApplication au rouleau, brosse ou mécanisée.\r\nPlâtres et dérivés bétons et dérivés, anciennes peintures adhérentes', 'Excellent pouvoir garnissant et opacifiant.\r\nFinition mate velours.\r\nGrande facilité d’application.\r\nBrillance à 60° : 5 U.B', '\r\n\r\nDensité : 1.46\r\nRendement : 10 - 12 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 3L, 15L\r\n\r\n', 45),
(60, 'Novabat velours ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/velours/novabat-velours/innova-novabat-velours_detour-510x565.png', 'Intérieur\r\nTravaux neufs et de rénovation\r\nApplication au rouleau, brosse ou mécanisée\r\nPlâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes', '\r\n\r\n    Bon pouvoir garnissant et opacifiant\r\n    Finition velours\r\n    Grande facilité d\'application\r\n    Brillance à 60° : 5 U.B\r\n\r\n', '\r\n\r\nDensité : 1,47\r\nRendement : 10-12m²/L\r\nBase : BLANC\r\nConditionnement : 15L\r\n\r\n', 50),
(61, 'Capitole Aqua Finish mat', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/mate/capitole-aqua-finish-mat/innova-capitole-aqua-finish-mat_15l050-280-510x701.jpg', 'Intérieur (Murs et Plafonds).\r\nTravaux neufs et rénovation.\r\nSpécial plafonds sans reprises.\r\nPlâtres et dérivés, anciennes peintures adhérentes', 'Sans tension Finition mate tendue exempte de reprises, même en lumière rasante et sur grandes surfaces Très bonne aptitude à la retouche Excellent pouvoir opacifiant même en 1 couche adhérence directe sur supports absorbants', '\r\n\r\nDensité : 1,65 Kg/dm3\r\nRendement :  12 - 14 m²/ L selon porosité du support.\r\nBase : BLANC\r\nConditionnement : 3L, 15L\r\n\r\n', 54),
(67, 'Capitole premium mat* (Blanc mat de capitole) ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/mate/capitole-premium-mat/innova-capitole-premium-mat-510x574.png', '\r\n\r\n    Intérieur\r\n    Travaux neufs et de rénovation y compris fond difficile\r\n    Application au rouleau, brosse\r\n    Spécial rénovation des plafonds douteux\r\n    Plâtres et dérivés, anciens badigeons et anciennes peintures adhérentes\r\n\r\n', 'Finition mat profond. Masque parfaitement les éventuelles imperfections du support\r\nExcellent pouvoir garnissant et opacifiant Grande facilité d’application Temps de         reprise important Possibilité d’application  mouillé sur mouillé\r\n    \r\n\r\n', '\r\n\r\n\r\n\r\n\r\nDensité : 1.48\r\nRendement : 8 - 10 m2/Kg\r\nBase : BLANC\r\nConditionnement : 2.5L rect, 20Kg\r\n\r\n', 47),
(76, 'Capitole aqua mat* (Mat aqua de capitole) ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/mate/capitole-aqua-mat/innova-capitole-aqua-mat-12-510x574.png', '\r\n\r\n    Intérieur\r\n    Travaux neufs et de rénovation\r\n    Pour murs et plafonds.\r\n    Plâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes\r\n\r\n', '\r\n\r\n    Finition mate tendue. Sans reprise.\r\n    Excellent pouvoir opacifiant.\r\n    Laisse respirer le support.\r\n    Non lustrable. Lessivable.\r\n    \r\n\r\n', '\r\n\r\nDensité :  1.50\r\nRendement : 12 - 14 m2/L\r\nBase : BLANC\r\nConditionnement : 3L, 12L\r\n\r\n', 25),
(77, 'Capitole classic mat* (Aubrac) ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/mate/capitole-classic-mat/innova-capitole-classic-mat-510x605.png', '\r\n\r\n    Intérieur.\r\n    Murs et plafonds – Fonction anti-taches.\r\n    Travaux neufs et de rénovation y compris fonds difficiles.\r\n    Application au rouleau, brosse.\r\n    Plâtres et dérivés, anciens badigeons et anciennes peintures adhérentes\r\n\r\n', '\r\n\r\n    Finition mat profond, masque les éventuelles imperfections du support\r\n    Excellent pouvoir garnissant et opacifiant\r\n    Grande facilité d’application, temps de reprise important\r\n    Faible odeur (formulé en milieu solvant isoparafinique)\r\n    ', '\r\n\r\nDensité : 1.57\r\nRendement : 10 - 12 m2/L\r\nBase : BLANC\r\nConditionnement : 3L, 15Kg\r\n\r\n', 59),
(87, 'Still \"classic\" mat* (Still acryl mat) ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/mate/still-mat-classic/still-classic-mat-510x559.png', 'Intérieur / Extérieur\r\nTravaux neufs et de rénovation y compris fond difficile.\r\nPour murs et plafonds.\r\nPlâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes.', 'Finition mat profond\r\nMasque parfaitement les éventuelles imperfections du support\r\nExcellent pouvoir garnissant et opacifiant\r\nPossibilité d\'application de 2 couches dans la journée\r\nRendement élevé\r\nBel aspect décoratif', '\r\n\r\nDensité : 1.65\r\nRendement : 12-14 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 1L, 3L, 15L\r\n\r\n', 50),
(88, 'Calanque mat profond ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/mate/calanque-mat-profond/calanque-mat-510x608.png', '\r\n\r\n    Intérieur\r\n    Travaux neufs et de rénovation y compris fond difficile\r\n    Application au rouleau, brosse\r\n    Spécial plafond\r\n    Plâtres et dérivés, anciennes peintures adhérentes\r\n\r\n', 'Fintion mat profond. Masque parfaitement les éventuelles imperfections du support\r\nExcellent pouvoir garnissant et opacifiant Grande facilité d\'application. Temps de       reprise important Brillance 85° : < 1U.B\r\n\r\n', '\r\n\r\nDensité : 1.55\r\nRendement : 10 à 12 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 1L, 3L, 15L\r\n\r\n', 53),
(90, 'Novalis mat ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/mate/novalis-acryl-mat/innova-novalis-render-acryl-mat-510x701.png', 'Intérieur\r\nMurs et plafonds\r\nTravaux neufs et rénovation\r\nPlâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes', '\r\n\r\n    Finition mate, soignée\r\n    Faible sensibilité au lustrage\r\n    Sans reprises, sans enbus\r\n    Temps de reprise élevé\r\n    Pouvoir opacifiant important\r\n    Grande blancheur\r\n    Brillance à 85° : <2,5 U.B\r\n\r\n', '\r\n\r\nDensité : 1,56\r\nRendement : 10-12m²/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 1L, 3L, 15L\r\n\r\n', 46),
(91, 'Novalis Matoxane ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/mate/novalis-matoxane/innova-novalis-render-matoxane-510x701.png', '\r\n\r\n    Intérieur\r\n    Murs et plafonds\r\n    Travaux neufs et de rénovation\r\n    Plâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes.\r\n\r\n', '\r\n\r\n    Finition mate, soignée\r\n    Aspect mat minéral. Laisse respirer le support\r\n    Sans reprises, sans embus\r\n    Temps de reprise élevé\r\n    Pouvoir opacifiant important\r\n    Grande blancheur\r\n    Brillance à 85° : < 2U.B\r\n\r\n', '\r\n\r\nDensité : 1.54\r\nRendement : 10-12m²/L\r\nBase : BLANC\r\nConditionnement : 43L, 15L\r\n\r\n', 48),
(100, 'Esterel gliss', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/mate/esterel-gliss/innova-esterel-gliss-510x701.png', '\r\n\r\n    Intérieur.\r\n    Travaux neufs et de rénovation.\r\n    Plâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes.\r\n\r\n', '\r\n\r\n    Aspect mat profond semi-tendu.\r\n    Bon pouvoir garnissant et opacifiant.\r\n    Possibilité d’application de 2 couches dans la journée.\r\n    Peut être appliqué directement en 2 couches sur placoplâtre neuf.\r\n    Brillance à 85° : < 1.5 U.B\r\n\r\n', '\r\n\r\nDensité : 1.59\r\nRendement : 6-8 m2/Kg (10-12 m2/L)\r\nBase : BLANC\r\nConditionnement : 3L, 15L\r\n\r\n', 49),
(101, 'Esterel mat', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/mate/esterel-mat/innova-esterel-mat-510x701.png', 'Intérieur.\r\nTravaux neufs et de rénovation.\r\nApplication manuelle ou mécanisée.\r\nPlâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes.', 'Aspect mat poché.\r\nBon pouvoir garnissant et opacifiant.\r\nPossibilité d’application de 2 couches dans la journée.\r\nSans odeur\r\nGrande blancheur', '\r\n\r\nDensité : 1.57\r\nRendement : 10-12 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 3L, 15L\r\n\r\n', 53),
(102, 'Novabat mat ', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/mate/novabat-mat/innova-novabat-mat_detour-510x565.png', '\r\n\r\n    Intérieur\r\n    Travaux neufs et de rénovation\r\n    Application manuelle ou mécanisée\r\n    Plâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes\r\n\r\n', '\r\n\r\n    Aspect mat poché\r\n    Bon pouvoir garnissant et opacifiant\r\n    Possibilité d\'application de 2 couches dans la journée\r\n    Sans odeur\r\n    Grande blancheur\r\n\r\n', '\r\n\r\nDensité : 1.61\r\nRendement : 10-12m²/L\r\nBase : BLANC\r\nConditionnement : 15L\r\n\r\n', 50),
(103, 'Novamat', 'https://www.peintures-innova.fr/thumbs/peintures/finitions/mate/novamat/novamat-510x701.png', '\r\n\r\n    Intérieur\r\n    Murs et plafonds - fonction anti-tâches\r\n    Travaux neufs et de rénovation y compris fonds difficiles\r\n    Application au rouleau, brosse\r\n    Plâtres et dérivés\r\n\r\n', 'Finition mat profond, masque les éventuelles imperfections du support Bon pouvoir garnissant Grande facilité d\'application, temps de reprise important Isolant des tâches  nicotine noir de fumée, tâches d\'humiditéSans tension Retapissable/ recouvrable\r\n\r\n', '\r\n\r\nDensité : 1.57\r\nRendement : 10-12m²/L\r\nBase : BLANC\r\nConditionnement : 15L\r\n\r\n', 52),
(104, 'ID structure', 'https://www.peintures-innova.fr/thumbs/peintures/peintures-decoratives/peinture-decoratives-a-effet/id-structure/id-structure-510x701.png', '\r\n\r\n    Intérieur\r\n    Travaux neufs et de rénovation\r\n    Application lisseuse inox ou couteaux à enduire souple\r\n    Plâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes\r\n\r\n', '\r\n\r\n    Application facile en 2 passes\r\n    Prêt à l\'emploi\r\n    Temps ouvert important\r\n    Lavable et lessivable\r\n\r\n', '\r\n\r\nDensité : 1.99\r\nRendement : 1,5 Kg/m²\r\nBase : BLANC\r\nConditionnement : 3L, 25Kg\r\n\r\n', 53),
(105, 'ID R PUR MAT', 'https://www.peintures-innova.fr/thumbs/peintures/peintures-decoratives/peinture-depolluante/id-r-pur-mat/innova-id-r-pur-10l-detoure_mat-510x701.png', '\r\n\r\n    Intérieur\r\n    Travaux neufs et de rénovation\r\n    Plâtres et dérivés, bétons, anciennes peintures adhérentes\r\n\r\n', '\r\n\r\n    Peinture dépolluante , détruit les formaldéhydes\r\n    1m² peint = 1m3 d\'air purifié en 24h\r\n    Excellent pouvoir couvrant et garnissant\r\n    Grande blancheur\r\n    Bon rendement\r\n    Possibilité d\'application de 2 couches dans la journée\r\n\r\n', '\r\n\r\nDensité : 1.59\r\nRendement : 10-12m²/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 0.75L, 2.5L, 10L\r\n\r\n', 54),
(106, 'ID R PUR Satin ', 'https://www.peintures-innova.fr/thumbs/peintures/peintures-decoratives/peinture-depolluante/id-r-pur-satin/innova-id-r-pur-10l-detoure_satin-510x701.png', '\r\n\r\n    Intérieur\r\n    Travaux neufs et de rénovation\r\n    Plâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes\r\n\r\n', '\r\n\r\n    Peinture dépolluante, détruit les formaldéhydes\r\n    1m² peint = 1m3 d\'air purifié en 24h\r\n    Excellent pouvoir couvrant et garnissant\r\n    Grande blancheur\r\n    Bon rendement\r\n    Possibilité d\'application de 2 couches dans la journée\r\n\r\n', '\r\n\r\nDensité : 1.58\r\nRendement : 10-12m²/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 0.75L, 2.5L, 10L\r\n\r\n', 58),
(107, 'ID R PUR Sous-couche', 'https://www.peintures-innova.fr/thumbs/peintures/peintures-decoratives/peinture-depolluante/id-r-pur-sous-couche/ssc-10l_idrpur_id-100x107.png', '\r\n\r\n    Intérieur\r\n    Travaux neufs et de rénovation\r\n    Plâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes\r\n\r\n', '\r\n\r\n    Peinture dépolluante, détruit les formaldéhydes\r\n    1m² peint = 1m3 d\'air purifié en 24h\r\n    Excellent pouvoir couvrant et garnissant\r\n    Grande blancheur\r\n    Bon rendement\r\n    Possibilité d\'application de 2 couches dans la journée\r\n\r\n', '\r\n\r\nDensité : 1.54\r\nRendement : 10-12m²/L\r\nBase : BLANC\r\nConditionnement : 0.75L, 2.5L, 10L\r\n\r\n', 63),
(128, 'Impression 1009 ', '\r\nhttps://www.peintures-innova.fr/thumbs/peintures/facade/impression-fixateur/impression-1009/impression-1009-510x559.png\r\n    \r\n\r\n', '\r\n\r\n    Extérieur.\r\n    Travaux neufs et de rénovation.\r\n    Particulièrement adapté pour les sous couches du système façade.\r\n    Bétons et dérivés, anciennes peintures adhérentes.\r\n\r\n', 'Bloque les fonds avant application des finitions.\r\nBon pouvoir opacifiant.\r\nRendement élevé.\r\nSéchage rapide : recouvrable dans la journée', '\r\n\r\nDensité : 1.49\r\nRendement : 10 - 12 m2/L\r\nBase : BLANC\r\nConditionnement : 3L, 15L\r\n\r\n', 70),
(129, 'Fixfon aqua', 'https://www.peintures-innova.fr/thumbs/peintures/facade/impression-fixateur/fixfon-aqua/fixfon-aqua-510x559.png', 'Extérieur.\r\nTravaux neufs et de rénovation\r\nFixation des fonds farinants\r\nBétons et dérivés, anciennes peintures adhérentes', 'Bon pouvoir garnissant et opacifiant.\r\nExcellente pénétration des fonds, favorisant l’adhérence\r\nFixe les fonds farinants\r\nMicroporeux – Insaponifiable', '\r\n\r\nDensité : 1.46\r\nRendement : 10-12 m2/L\r\nBase : BLANC\r\nConditionnement : 3L, 15L\r\n\r\n', 68),
(130, 'Fixfon opaque', 'https://www.peintures-innova.fr/thumbs/peintures/facade/impression-fixateur/fixon-opaque/fixfon-opaque-510x559.png', 'Extérieur.\r\nTravaux neufs et de rénovation.\r\nFixation des fonds farinant et pulvérulents.\r\nBétons et dérivés, bardage métalliques, anciennes peintures adhérentes', 'Bon pouvoir garnissant et opacifiant.\r\nExcellente pénétration des fonds, favorisant l’adhérence.\r\nFixe les fonds farinant.\r\nMicroporeux – Insaponifiable.\r\nConvient pour sous couches sur les bardages bruts ou prépeints', '\r\n\r\nDensité : 1.46\r\nRendement : 8 - 10 m2/L\r\nBase : BLANC\r\nConditionnement : 3L, 15L\r\n\r\n', 65),
(131, 'Novalite', 'https://www.peintures-innova.fr/thumbs/peintures/facade/film-mince-d2/novalite/novalite-510x559.png', 'Extérieur.\r\nTravaux neufs et de rénovation.\r\nBien adapté sur les fonds difficiles, consolide les fonds farinants.\r\nConvient pour les soubassements.\r\nBétons et dérivés, supports minéraux, anciennes peintures adhérentes', '\r\n\r\n    Excellent pouvoir couvrant.\r\n    Aspect mat, sans reprises ni embus.\r\n    Excellente adhérence sur fonds poreux.\r\n    Microporeux. Insaponifiable.\r\n    Bonne résistance aux intempéries et aux U.V.\r\n\r\n', '\r\n\r\nDensité : 1.48\r\nRendement : 8 - 10 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 3L, 15L\r\n\r\n', 64),
(132, 'Novalite aqua ', 'https://www.peintures-innova.fr/thumbs/peintures/facade/film-mince-d2/novalite-aqua/novalite-aqua2-510x606.png', 'Extérieur.\r\nTravaux neufs et de rénovation.\r\nBien adapté sur les fonds difficiles consolide les fonds farinants\r\nConvient pour les soubassements\r\nBétons et dérivés, supports minéraux anciennes peintures adhérentes', '\r\n\r\n    Excellent pouvoir garnissant et opacifiant.\r\n    Aspect mat, sans reprises ni embus.\r\n    Excellente adhérence.\r\n    Microporeux.\r\n    Bonne résistance aux intempéries et aux U.V.\r\n\r\n', '\r\n\r\nDensité : 1.54\r\nRendement : 10 - 12 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement :  3L, 15L\r\n\r\n', 52),
(133, 'Novabardage aqua', 'https://www.peintures-innova.fr/thumbs/peintures/facade/film-mince-d2/novabardage-aqua/novabardage-aqua-510x559.png', '\r\n\r\n    Extérieur.\r\n    Travaux neuf et de rénovation.\r\n    Décoration et protection des bardages pré-laqués ou galvanisés.\r\n\r\n', '\r\nFinition satin doux semi tendue Facilité d’application et d’entretien Double fonction (primaire et finition) Résistant aux U.V. et aux intempéries.Très bonne résistance à l’eau Bonne résistance aux chocs et aux rayures. Souplesse de revêtement. \r\n\r\n', '\r\n\r\nDensité : 1.30\r\nRendement : 10 - 12 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 3L, 15L\r\n\r\n', 64),
(143, 'Pliolite 4010', 'https://www.peintures-innova.fr/thumbs/peintures/facade/film-mince-d2/pliolite-4010/pliolite_4010-443x484.png', '\r\n\r\n    Extérieur\r\n    Travaux neufs et de rénovation\r\n    Bien adapté sur les fonds difficiles, consolide les fonds farinants\r\n    Convient pour les soubassements.\r\n    Bétons et dérivés, supports minéraux, anciennes peintures adhérentes\r\n\r\n', '\r\n\r\n    Excellent pouvoir garnissant.\r\n    Aspect mat, sans reprises ni embus.\r\n    Excellente adhérence sur fonds poreux.\r\n    Microporeux. Insaponifiable.\r\n    Bonne résistance aux intempéries et aux U.V.\r\n\r\n', '\r\n\r\nDensité : 1.48\r\nRendement : 8 - 10 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 15L\r\n\r\n', 60),
(144, 'Novasyl', '\r\nhttps://www.peintures-innova.fr/thumbs/peintures/facade/film-mince-d2/novasyl/novasyl-510x559.png\r\n   \r\n', '    \r\n    Intérieur / Extérieur.\r\n    Travaux neufs et de rénovation.\r\n    Bien adapté aux applications mécanisées.\r\n    Plâtres et dérivés, bétons et dérivés, anciennes peintures adhérentes.', 'Excellent garnissant.\r\nAspect mat poché, sans reprises ni embus.\r\nGrande facilité d’application. Sans odeur.\r\nExtrait sec élevé', '\r\n\r\nDensité : 1.77\r\nRendement :  8 - 10 m2/Kg\r\nBase : BLANC - INCOLORE\r\nConditionnement :  3L, 25Kg\r\n\r\n', 60),
(145, 'Novaxane', 'https://www.peintures-innova.fr/thumbs/peintures/facade/peinture-minerale-organo-minerale/novaxane-d3/novaxane2-510x606.png', 'Extérieur.Travaux neufs et de rénovation.\r\nRavalement de façade sur supports neufs, anciennes peintures adhérentes, enduits     hydrauliques, RPE et RSE.Peinture minérale pour la mise en peinture des monuments historiques (conforme NF T 30-808)\r\n\r\n', 'Aspect mat minéral.\r\nMicroporosité élevée.\r\nHydrofuge. Effet perlant\r\nFaible susceptibilité à l\'encrassement et aux salissures biologiques.\r\nTrès bonne protection contre les eaux de ruissellement', '\r\n\r\nDensité : 1.70\r\nRendement : 650 - 750 gr/m2\r\nBase : BLANC - INCOLORE\r\nConditionnement : 3L, 25Kg\r\n\r\n', 62),
(146, 'Novaperle ', 'https://www.peintures-innova.fr/thumbs/peintures/facade/peinture-minerale-organo-minerale/novaperle/novaperle-510x559.png', 'Extérieur.\r\nTravaux neufs et de rénovation.\r\nRavalement de façade, sur support neuf, anciennes peintures adhérentes, enduits hydrauliques, RPE.\r\nAdaptée pour les applications mécanisées', '\r\n\r\n    Aspect mat.\r\n    Microporosité élevée.\r\n    Hydrofuge. Effet perlant.\r\n    Faible susceptibilité à l’encrassement et aux salissures biologiques.\r\n\r\n', '\r\n\r\nDensité : 1.70\r\nRendement : 8-10 m2/L\r\nBase :  BLANC\r\nConditionnement :  3L, 25Kg\r\n\r\n', 66),
(147, 'Novaflex D2-D3 ', 'https://www.peintures-innova.fr/thumbs/peintures/facade/semi-epais-d3/novaflex-d3/novaflex2-510x602.png', 'Extérieur.\r\nTravaux neufs et de rénovation.\r\nPour ravalement de façade sur enduit au mortier, fibrociment, béton, briques de parement, anciennes peintures adhérentes, enduits hydrauliques, RPE et RSE.\r\nProtection des supports faïencés', 'Existe en finition mate et satin velouté.\r\nFaible susceptibilité à l’encrassement.\r\nTrès bonne protection contre les eaux de ruissellement.\r\nExcellente résistance aux U.V. et aux intempéries', '\r\n\r\nDensité : 1.51\r\nRendement : 600 - 650 g/m2\r\nConditionnement : 3L, 15L\r\n\r\n', 67),
(148, 'Dermaxane D3/I1 ', 'https://www.peintures-innova.fr/thumbs/peintures/facade/semi-epais-d3/dermaxane-d3-i1/dermaxane-510x559.png', '\r\n\r\n    Extérieur.\r\n    Travaux neufs et de rénovation.\r\n    Pour ravalement de façade sur enduit au mortier, fibrociment, béton, briques de parement, anciennes peintures adhérentes, enduits hydrauliques.\r\n\r\n', '\r\n\r\nProtection et décoration des façades (masque le faïençage).Aspect mat minéral.Complément d’imperméabilité I1.Microporeux, renforcé aux siloxanes.Faible susceptibilité à l’encrassement Très bonne protection contre les eaux de ruissellement Garnissant\r\n', '\r\n\r\nDensité : 1.50\r\nRendement : 700 - 750 gr/m2\r\nBase : BLANC - INCOLORE\r\nConditionnement : 3L, 15L\r\n\r\n', 75),
(149, 'Novaderme', 'https://www.peintures-innova.fr/thumbs/peintures/facade/revetement-d-impermeabilite-i1-i2-i3-i4/novaderme/novaderme-510x559.png', 'Extérieur.\r\nTravaux neufs et de rénovation.\r\nPour ravalement de façade sur enduit au mortier, fibrociment, béton, briques de parement, anciennes peintures adhérentes, enduits hydrauliques, RSE.\r\nSystème d’imperméabilité de façade', 'Existe en finition mate et satin Bonne perméabilité à la vapeur d’eau.Très bonne protection contre les eaux de ruissellement.Excellente résistance aux U.V. et aux intempéries.Existe en traitement fongicide/algicide sur commande.\r\n\r\n', '\r\n\r\nDensité : 1.50\r\nRendement :  voir fiche technique\r\nBase :    BLANC - INCOLORE\r\nConditionnement : 3L, 15L\r\n\r\n', 49),
(150, 'Novagranit', 'https://www.peintures-innova.fr/thumbs/peintures/facade/revetement-plastique-epais-r-p-e/novagranit/novagranit-510x530.png', 'Extérieur.\r\n Revêtement plastique épais pour la décoration et la protection des maçonneries, supports neufs et anciens de nature minérale, tels que enduit ciment, béton, fibrociment..\r\n\r\n', '\r\n\r\n    Bonne résistance aux intempéries.\r\n    Perméable à la vapeur d’eau.\r\n    Masque le faïençage éventuel du support.\r\n    Existe en 5 finitions : à gréser, à talocher, projection, moyen, poché.\r\n\r\n', '\r\n\r\nDensité :1.87\r\nRendement : voir fiche technique\r\nBase : BLANC - INCOLORE\r\nConditionnement : 3L, 25Kg\r\n\r\n', 85),
(151, 'Béton égalisateur de fond ', 'https://www.peintures-innova.fr/thumbs/peintures/facade/lasure-beton/novalazure-egaliseur-de-fond-beton/beton-egalisateur-de-fond-510x559.png', 'Extérieur.\r\nTravaux neufs et de rénovation.\r\nDécoration et protection des bétons bruts de décoffrage', 'Atténue les défauts de surface.\r\nRégule les fonds béton avant la finition NOVALAZURE BETON', '\r\n\r\nDensité : 1.70\r\nRendement : 8 - 10 m2/L\r\nBase : GRIS CIMENT\r\nConditionnement : 15L\r\n\r\n', 73),
(164, 'Béton Novalazure', 'https://www.peintures-innova.fr/thumbs/peintures/facade/lasure-beton/novalazure-beton/beton-novalazure2-510x559.png', 'Extérieur Travaux neufs et de rénovation.Décoration et protection des bétons bruts de décoffrage gris ou blancs préfabriqués ou coulés Valorise les supports béton en atténuant leurs défauts et en leur conférant une protection hydrofuge', 'Aspect satiné.\r\nColore et fait ressortir les nuances naturelles du béton.\r\nExiste en finition lasure transparent ou opaque.\r\nRégule et uniformise les supports béton', '\r\n\r\nDensité : 0.87\r\nRendement :  6 - 10 m2/L\r\nBase :  INCOLORE\r\nConditionnement : 3L, 15L\r\n\r\n', 40),
(165, 'Novatoit', 'https://www.peintures-innova.fr/thumbs/peintures/facade/toiture/novatoit/novatoit-510x559.png', 'Extérieur.Travaux neufs et de rénovation.Toute toiture de pente supérieure à 5% assurant le libre écoulement des eaux de pluie.Tuiles béton, tuiles terre cuite fibrociment,bitumineux, ardoises artificielles ou naturelles, anciennes peintures en bon état.\r', 'Aspect mat velouté.Protège et imperméabilise les toitures.Excellent pouvoir couvrant et garnissant Large polyvalence d’emploi  Bonne tenue U.V\r\n\r\n', '\r\n\r\nDensité : 1.36\r\nRendement :  250 - 350 g/m2\r\nBase :   INCOLORE - GRIS ARDOISE - ROUGE BRIQUE\r\nConditionnement :  3L, 15L\r\n\r\n', 65),
(166, 'Hydrofuge innova H224 ', '\r\nhttps://www.peintures-innova.fr/thumbs/peintures/facade/hydrofuge-antimousse/hydrofuge-innova-h224/hydrofuge-aqua-510x510.png\r\n', 'Extérieur.\r\nTous supports minéraux poreux nécessitant une hydrofugation tels que : pierres briques bétons, enduits...\r\nApplication au rouleau ou pulvérisateur basse pression jusqu’à saturation du support.\r\n', 'Prêt à l’emploi.\r\nRalentit l’encrassement des fonds traités.\r\nDiminue les risques de dégâts dus au gel – dégel.\r\nMicroporeux.\r\nEffet perlant', '\r\n\r\nDensité : 0.80\r\nRendement : 3 - 5 m2/L suivant porosité du support\r\nBase :  INCOLORE\r\nConditionnement : 5L, 25L\r\n', 67),
(167, 'Novacide Pro ', 'https://www.peintures-innova.fr/thumbs/peintures/facade/hydrofuge-antimousse/novacide/novacide-510x782.png', 'Extérieur.\r\nPour un traitement anti-dépôts verts des façades et des toitures', '\r\n\r\n    Produit concentré, peut être dilué par 3x son volume.\r\n    Effets curatifs et préventifs sur les mousses, lichens, algues\r\n    Application par pulvérisation des supports à traiter\r\n\r\n', '\r\n\r\nDensité : 1\r\nRendement : 4m2/L\r\nBase :  Solution bleutée\r\nConditionnement : 5L, 20L\r\n\r\n', 62),
(168, 'ID Hydrofuge aqua ', 'https://www.peintures-innova.fr/thumbs/peintures/facade/hydrofuge-antimousse/hydrofuge-aqua/id_hydrofuge_aqua-510x701.png', 'Extérieur.\r\nTous supports minéraux poreux nécessitant une hydrofugation tel que : pierres, briques, bétons, enduits…\r\n Application au rouleau ou pulvérisateur basse pression jusqu’à saturation du support.', 'Prêt à l’emploi\r\n Ralentit l’encrassement des fonds traités\r\n Diminue les risques de dégâts dus au gel – dégel\r\n Microporeux\r\n Effet perlant', '\r\n\r\nDensité : 1\r\nRendement :  2-5 m2/L\r\nBase :  INCOLORE\r\nConditionnement : 2.5L, 5L\r\n\r\n', 64),
(169, 'Novagranit siloxane ', 'https://www.peintures-innova.fr/thumbs/peintures/facade/revetement-mineral-epais-r-m-e/novagranit-siloxane/novagranit-510x530.png', ' Extérieur.\r\n    Revêtement minéral épais pour la décoration et la protection des maçonneries, supports neufs et anciens de nature minérale, tels que enduit ciment, béton, fibrociment...\r\n\r\n', 'Bonne résistance aux intempéries.\r\nPerméable à la vapeur d’eau.\r\nRevêtement de façades de classe D3.\r\nMasque le faïençage éventuel du support.\r\nTaloché fin - Granulométrie 0.7 mm', '\r\n\r\nDensité : 1.87\r\nRendement :  2 - 2.2 Kg/m2\r\nBase :  BLANC - INCOLORE\r\nConditionnement :  3L, 25Kg\r\n\r\n', 70),
(170, 'Capitole classic impression ', 'https://www.peintures-innova.fr/thumbs/peintures/bois-vernis/impression-saturateur/capitole-classic-impression/innova-capitole-classic-imp-510x605.png', 'Intérieur/Extérieur\r\nTravaux neufs et de rénovation.\r\nParticulièrement adapté sur boiseries en sous-couche de laques glycero.\r\nPlâtres et dérivés, bois et dérivés, anciennes peintures adhérentes, bois et dérivés intérieur/Extérieur.', 'Bon pouvoir opaciﬁant\r\nForte action pénétrante microporeuse\r\nFacilité d’application Garnissante\r\nBloque et durcie les fonds\r\nLongue en huile, excellente durabilité', '\r\n\r\nDensité :  1.45\r\nRendement :  10-12 m2/L\r\nBase :  BLANC\r\nConditionnement : 0.75L, 3L, 15L\r\n\r\n', 61),
(171, 'Capitole aqua primaire universel ', 'https://www.peintures-innova.fr/thumbs/peintures/bois-vernis/impression-saturateur/capitole-aqua-primaire-universel/innova-capitole-aqua-primai-510x574.png', 'Intérieur/Extérieur.\r\nTravaux neufs et de rénovation.\r\nSur tout supports usuels du bâtiment : bois et dérivés, métaux ferreux et non ferreux, plâtre et dérivés, bétons et dérivés, PVC, anciennes peintures adhérentes', 'Excellente adhérence.Excellent pouvoir opaciﬁant. Aspect tendu. Bloque les remontées de tanins.Recouvrable dans la journée.Contient un inhibiteur de corrosion et un agent anti-tannique.Bloque et durcie les fonds', '\r\n\r\nDensité : 1.38\r\nRendement :  10-12 m2/L\r\nBase :  BLANC\r\nConditionnement :  1L, 3L, 12L\r\n\r\n', 69),
(172, 'Capitole premium brillant ', 'https://www.peintures-innova.fr/thumbs/peintures/bois-vernis/peinture-microporeuse-de-finition/capitole-premium-brillant/innova-capitole-premium-bri-510x574.png', 'Intérieur / Extérieur.\r\nTravaux neufs et de rénovation.\r\nApplication au rouleau laqueur ou à la brosse.\r\nPlâtres et dérivés, bétons et dérivés, bois et dérivés, anciennes peintures adhérentes .\r\nSpécialement adapté pour les boiseries extérieures', 'Excellent pouvoir garnissant et opacifiant.Aspect brillant tendu.Lessivable, facilité d’entretien.Microporeuse. Longue en huile.Grande facilité d’application. Rendement élev Bonne résistance aux intempéries et aux U.V. Brillance à 20° : > 90 U.B', '\r\n\r\nDensité : 1.21\r\nRendement : 14 - 16 m2/L\r\nBase :   BLANC - INCOLORE\r\nConditionnement :  750.75L, 3L, 12L\r\n\r\n', 75),
(173, 'Capitole premium satin', 'https://www.peintures-innova.fr/thumbs/peintures/bois-vernis/peinture-microporeuse-de-finition/capitole-premium-satin/innova-capitole-premium-sat-510x574.png', 'Intérieur/Extérieur.\r\nTravaux neufs et de rénovation.\r\nApplication au rouleau laqueur ou à la brosse.\r\nPlâtres et dérivés, bois et dérivés, anciennes peintures adhérentes.\r\nSpécialement adapté pour les boiseries extérieures', 'Excellent pouvoir garnissant et opacifiant.\r\nAspect satin tendu.\r\nLessivable, facilité d’entretien.\r\nMicroporeuse.\r\nGrande facilité d’application. Rendement élevé.\r\nBrillance à 60° : 25 U.B', '\r\n\r\nDensité : 1.45\r\nRendement :  16-18 m2/L\r\nBase :   BLANC - INCOLORE\r\nConditionnement :  0.75L, 3L, 12L\r\n\r\n', 76),
(174, 'Capitole aqua satin ', 'https://www.peintures-innova.fr/thumbs/peintures/bois-vernis/peinture-microporeuse-de-finition/capitole-aqua-satin/innova-capitole-aqua-satin-510x574.png', 'Intérieur/Extérieur.\r\nTravaux neufs et de rénovation.\r\nApplication aux rouleaux laqueurs.\r\nPlâtres et dérivés, bétons et dérivés, bois et dérivés, anciennes peintures adhérentes. Spécial boiseries intérieures.', 'Bon pouvoir opacifiant Aspect satin tendu Excellente dureté, lessivable, facilité d’entretien Séchage hors poussières 30mn Excellente résistance aux U.V. Sans odeur Brillance à 60° : 20 U.B', '\r\n\r\nDensité : 1.38\r\nRendement : 12-14 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement :  1L, 3L, 12L\r\n\r\n', 28),
(175, 'Bois lazure ', 'https://www.peintures-innova.fr/thumbs/peintures/bois-vernis/lasure/bois-lazure/innova-bois-lazure-render-07-510x701.jpg', 'Intérieur/Extérieur.\r\nTravaux neufs et de rénovation.\r\nDécoration et protection du bois', 'Aspect satiné ciré transparent valorisant le veinage du bois.\r\nMicroporeux. Confort d’application grâce à sa structure gélifiée. Excellente résistance aux intempéries. Protection U.V.\r\n\r\n', '\r\n\r\nDensité : 0.90\r\nRendement :  10-14m2/L\r\nBase :   INCOLORE - 7 teintes bois\r\nConditionnement :  0.75L, 3L, 10L\r\n\r\n', 30),
(176, 'Bois Lazure Aqua Saturateur ', 'https://www.peintures-innova.fr/thumbs/peintures/bois-vernis/lasure/bois-lazure-aqua-saturateur/bois-lazure-aqua-saturateur-510x701.png', '\r\n\r\n    Intérieur / Extérieur\r\n    Travaux neufs et de rénovation\r\n    Décoration et protection du bois\r\n    Terrasses, caillebotis, toutes essences de bois couramment utilisées : Bois exotiques,    feuillus européens, bois résineux\r\n\r\n', '\r\n\r\n    Pénétrant et non filmogène\r\n    Effet hydroperlant assurant une protection renforcée contre les intempéries\r\n    Ne s\'écaille pas et garde l\'aspect naturel du bois\r\n    Disponible en 7 teintes\r\n\r\n', '\r\n\r\nDensité : 1\r\nRendement : 10-15 m²/L\r\nBase : INCOLORE et 7 Teintes\r\nConditionnement : 3L, 10L\r\n\r\n', 31),
(177, 'Bois Lazure aqua ', 'https://www.peintures-innova.fr/thumbs/peintures/bois-vernis/lasure/bois-lazure-aqua/bois_lazure_aqua-510x701.png', '\r\n\r\n    Intérieur/Extérieur.\r\n    Travaux neufs et de rénovation.\r\n    Décoration et protection du bois.\r\n\r\n', '\r\n\r\n    Aspect satiné ciré transparent valorisant le veinage du bois.\r\n    Confort d’application grâce à sa structure gélifiée.\r\n    Excellente résistance aux intempéries. Protection U.V.\r\n    Sans odeur.\r\n\r\n', '\r\n\r\nDensité : 1.05\r\nRendement : 10 - 14 m2/L\r\nBase : INCOLORE - 7 teintes bois\r\nConditionnement : 0.75L, 3L, 12L\r\n\r\n', 32),
(178, 'Huile Flamande ', 'https://www.peintures-innova.fr/thumbs/peintures/bois-vernis/lasure/huile-flamande/huile-flamande-510x701.png', 'Extérieur.\r\nTravaux neufs et de rénovation.\r\nImprégnation et protection du bois.\r\nPour bois exotique et de haute montagne', 'Aspect satiné incolore non filmogène. Microporeux.\r\nRavive la couleur naturelle du bois.\r\nExcellente résistance aux intempéries.\r\nHydrofuge.\r\nNon filmogène', '\r\n\r\nDensité : 0.90\r\nRendement : 10-14 m2/L\r\nBase : INCOLORE\r\nConditionnement : 0.75L, 3L, 10L\r\n\r\n', 35),
(179, 'Vernis marin ', 'https://www.peintures-innova.fr/thumbs/peintures/bois-vernis/vernis/vernis-marin/vernis-marin-510x559.png', '\r\n\r\n    Extérieur.\r\n    Travaux neufs et de rénovation.\r\n    Décoration et protection du bois.\r\n    Particulièrement adapté pour travaux en bord de mer et en climat de montagne.\r\n\r\n', '\r\n\r\n    Aspect brillant transparent tendu.\r\n    Excellente résistance aux intempéries.\r\n    Protection U.V. Hydrofuge. Lavable.\r\n    Conserve au bois l’aspect de sa structure naturelle.\r\n\r\n', '\r\n\r\nDensité :  0.90\r\nRendement :   12 - 15 m2\r\nBase :  INCOLORE\r\nConditionnement :  0.75L, 3L\r\n\r\n', 34);
INSERT INTO `paints` (`id`, `title`, `cover`, `destination`, `features`, `description`, `price`) VALUES
(180, 'Vernis aqua PU 2K ', 'https://www.peintures-innova.fr/thumbs/peintures/bois-vernis/vernis/vernis-aqua-pu/vernis-pu-2k-aqua-510x701.png', 'Intérieur / ExtérieurTravaux neufs et de rénovation Bois et dérivés, bétons et dérivés, enduits décoratifs, parquets bois, faïence, plastique, polyester Idéal pour la protection des enduits décoratifs sols etls que notre ID TADELAKT ou des bétons cirés', '\r\n\r\n    Vernis translucide tendu\r\n    Dureté extrême et bonne souplese\r\n    Grande résistance aux rayures\r\n    Excellente résistance aux produits chimiques ménagers\r\n    Temps ouvert important, pas de risque de reprises lors de l\'application\r\n\r\n', '\r\n\r\nDensité : 1.05\r\nRendement : 10 - 15 m²/L\r\nBase : INCOLORE\r\nConditionnement :  1L, 3L\r\n\r\n', 37),
(221, 'Novathane ', 'https://www.peintures-innova.fr/thumbs/peintures/sols/domestique/novathane/novathane-510x559.png', 'Intérieur/Extérieur.\r\nTravaux neufs et de rénovation.\r\nDécoration et protection des sols à usage domestique : garage, escalier, balcon, terrasse...\r\n\r\n', 'Aspect satiné.\r\nFacilité d’application et d’entretien.\r\nApplication multicouches directe.\r\nBonne dureté, résistant à l’abrasion.\r\nBonne tenue à l’eau et aux détergents ménagers usuels', '\r\n\r\nDensité : 1.25\r\nRendement : 10 - 12m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 0.75L, 3L, 15L\r\n\r\n', 48),
(222, 'Novathane aqua 2K ', 'https://www.peintures-innova.fr/thumbs/peintures/sols/domestique/novathane-aqua-2k/novathane-aqua-2k-510x701.png', 'Intérieur/Extérieur.\r\nTravaux neufs et de rénovation.\r\nDécoration et protection des murs et sols.\r\nBois et dérivés, bétons et dérivés, parquets bois, faïence, plastique, polyester..\r\n', 'Aspect tendu. Finition satinée\r\nExcellente résistance aux U.V.\r\nBonne résistance à l’abrasion et à la rayure.\r\nAdhérence exceptionnelle en direct sur tout support.\r\nBonne résistance chimique', '\r\n\r\nDensité : 1.40\r\nRendement : 12 - 14 m2/L\r\nBase :  BLANC - INCOLORE\r\nConditionnement : 1L, 3L, 12L\r\n\r\n', 50),
(223, 'Novepox 1450 ', 'https://www.peintures-innova.fr/thumbs/peintures/sols/industriel/novepox-1450/novepox-1450-510x701.png', 'Intérieur.Bétons et dérivés, plâtres et dérivés, anciennes peintures adhérentes.\r\nRecommandé pour les sols industriels et les murs en particulier quand on désire des résistances chimiques ou à l’abrasion importante', 'Excellente résistance chimique.Excellente résistance à l’abrasion.Bonne résistance à l’essence gasoil solvant détergentFaible sensibilité à l’encrassement bonne résistance aux produits de nettoyages usuels Adapté aux locaux à exigences d’hygiène élevées', '\r\n\r\nDensité : 1.48\r\nRendement : 8-10 m²\r\nBase :  BLANC - INCOLORE\r\nConditionnement :  3L, 12L\r\n\r\n', 60),
(224, 'Novepox semi-épais ', 'https://www.peintures-innova.fr/thumbs/peintures/sols/industriel/novepox-semi-epais/novepox-hes-510x559.png', 'Intérieur Bétons et dérivés, enrobé percolé, carrelage préalablement apprêté.\r\nDestiné aux locaux soumis à un trafic intense : Parking, sols industriels, entrepôts, garages\r\n\r\n', '\r\nExcellente résistance à l’abrasion, aux chocs.Bonne résistance à un grand nombre de produits chimiques.Haut extrait sec (98% ES) Application au rouleau ou à la raclette.\r\nAuto-nivelant.\r\n\r\n', '\r\n\r\nDensité : 1.82\r\nRendement :  250 - 350 g/m2\r\nBase : BLANC - INCOLORE\r\nConditionnement :  20Kg\r\n\r\n', 65),
(225, 'Novepox multicouche ', 'https://www.peintures-innova.fr/thumbs/peintures/sols/industriel/novepox-multicouche/novepox-mc-510x559.png', 'Intérieur Bétons et dérivés carrelage préalablement préparé. Primaire d\'accrochage pour systèmes époxy pour sols Parking, sols industriels entrepôts garages Résine pour la réalisation de Tiré à Zéro de mortier de rebouchage epoxy\r\n\r\n', 'Excellente résistance mécanique\r\nExcellente adhérence Haut extrait sec (98% ES)\r\nApplication primaire de notre EPOXY SEMI-EPAIS\r\nA mélanger avec de la silice pour rattraper la planéité du support Autolissant', '\r\n\r\nDensité : 1.07\r\nRendement : Primaire: 350 - 400 g/m2 - Couche de masse: 1.6 à 2Kg/mm/m2 - Mortier : 2.2 Kg/mm/m2\r\nBase : INCOLORE\r\nConditionnement : 25Kg\r\n\r\n', 67),
(226, 'Vernis aqua pu 2K ', 'https://www.peintures-innova.fr/thumbs/peintures/sols/parquet-bois/vernis-pu-aqua-2k/vernis-aqua-pu-2k-510x701.png', 'Intérieur Extérieur Travaux neufs et de rénovation.Bois et dérivés, bétons et dérivés\r\nplâtres et dérivés métaux ferreux et non ferreux anciennes peintures adhérentes.Idéal pour la protection des enduits décoratifs sols tel que notre ID TADELAKT', 'Vernis translucide tendu.Dureté extrême et bonne souplesse.Grande résistance aux rayures.\r\nExcellente Résistance aux U.V.Grande résistance aux produits chimiques ménagers.Temps ouvert important, pas de risque de reprise lors de l\'application', '\r\n\r\nDensité : 1.05\r\nRendement : 10-15 m²/L\r\nBase : INCOLORE\r\nConditionnement : 1L, 3L, 12L\r\n\r\n', 70),
(227, 'Vernis parquet', 'https://www.peintures-innova.fr/thumbs/peintures/sols/parquet-bois/vernis-parquet/vernis-parquet-510x559.png', '\r\n\r\n    Intérieur.\r\n    Travaux neufs et de rénovation.\r\n    Décoration et protection des sols bois à usage domestique : parquet, escalier...\r\n\r\n', 'Existe en finition satinée ou brillante.\r\nFacilité d’application et d’entretien.\r\nBonne dureté, résistant à l’abrasion.\r\nBonne tenue à l’eau et aux détergents ménagers usuels', '\r\n\r\nDensité : 0.98\r\nRendement : 12 - 14 m2/L\r\nBase :  INCOLORE\r\nConditionnement :   0.75L, 3L, 10L\r\n\r\n', 64),
(228, 'Novatennis ', 'https://www.peintures-innova.fr/thumbs/peintures/sols/sol-sportif/novatennis/novatennis-510x701.png', 'Intérieur/Extérieur.\r\nTravaux neufs et rénovation.\r\nPour mise en peinture ou marquage de sols sportifs et circulations piétonnières : sur béton, ciment, bitume, asphalte, revêtement synthétique.\r\n\r\n', '\r\n\r\n    Aspect satiné rugueux.\r\n    Antidérapant.\r\n    Bonne résistance à l’usure.\r\n    Bonne tenue U.V. et intempéries (garde longtemps la qualité de ses teintes).\r\n\r\n', '\r\n\r\nDensité : 1.56\r\nRendement : 200 - 250 g/m2\r\nBase :   INCOLORE - BLANC - OXYDE VERT - OXYDE ROUGE\r\nConditionnement :  3L, 15L\r\n\r\n', 62),
(229, 'Novapiscine ', 'https://www.peintures-innova.fr/thumbs/peintures/sols/piscine/novapiscine/novapiscine-510x701.png', '\r\n\r\n    Extérieur.\r\n    Bétons et dérivés.\r\n    Pour ambiance chimique agressive, maritime ou industrielle.\r\n    Revêtement de surfaces immergées : piscines, réservoirs d’eau non potable...\r\n\r\n', '\r\n\r\n    Aspect satin.\r\n    Excellente résistance aux chlores.\r\n    Bonne résistance aux acides et aux bases.\r\n    Bonne résistance aux produits chimiques.\r\n    Insaponifiable : application possible sur fonds alcalins.\r\n\r\n', '\r\n\r\nDensité : 1.41\r\nRendement : 8 - 10 m2/L\r\nBase :  BLANC - INCOLORE - BLEU PISCINE\r\nConditionnement :   3L, 15L\r\n\r\n', 58),
(230, 'Fixofer primaire (Antirouille 80)', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/primaire-anticorrosion/fixofer-primaire/fixofer-510x548.png', 'Intérieur/Extérieur.\r\nTravaux neufs et de rénovation\r\nDirectement sur métaux ferreux préalablement préparés', 'Finition brillant et satinée.\r\nSéchage rapide.\r\nExcellente protection anticorrosion (riche en pigment anticorrosion).\r\nSystème anticorrosion (5 ans cliché 7) avec en finition notre produit FIXOFER', '\r\n\r\nDensité : 1.48\r\nRendement :  8 - 10 m2/L\r\nBase :  BLANC - ROUGE BRUN - GRIS CLAIR\r\nConditionnement : 0.75L, 3L, 15L\r\n\r\n', 66),
(231, 'Appret 3000 XS ', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/primaire-anticorrosion/appret-3000/appret-3000-xs-510x701.png', 'Extérieur.\r\nMétaux ferreux.\r\nRecouvrable par toute peinture (sauf époxy).\r\nAtmosphères : rurale, urbaine, non corrosive.\r\nIndétrempable', 'Aspect mat velouté.Séchage rapide.Bonne propriété anticorrosion (riche en pigment anticorrosion).Temps de recouvrement très rapide.Excellentes propriétés mécaniques dureté adhérence Excellent pouvoir couvrant', '\r\n\r\nDensité : 1.43\r\nRendement : 8m2/L sous 40µm\r\nBase :  BLANC - INCOLORE - OCRE - ROUGE BRUN - GRIS CLAIR\r\nConditionnement : 3L, 20Kg\r\n\r\n', 80),
(232, 'Appret 3100 XS ', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/primaire-anticorrosion/appret-3100/appret-3100-xs-510x701.png\r\n    \r\n\r\n', 'Extérieur.\r\nMétaux ferreux.\r\nAtmosphères : rurale, urbaine, non corrosive.\r\nPrimaire de finition', 'Aspect satin douxSéchage rapide.Bonne propriété anticorrosion (80μm sec minimum).\r\nTemps de recouvrement très rapide Haut extrait sec. Permet de déposer jusqu’à 80μm sans coulures Excellentes propriétés mécaniques dureté adhérence\r\n\r\n', '\r\n\r\nDensité : 1.45\r\nRendement : 8 m2/L sous 40μm\r\nBase : BLANC - INCOLORE - ROUGE BRUN - GRIS CLAIR\r\nConditionnement :  3L, 20Kg\r\n\r\n', 85),
(233, 'Appret 3300 WS', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/primaire-anticorrosion/appret-3300/appret-3300-xs-510x701.png', '\r\n\r\n    Intérieur / Extérieur\r\n    Métaux ferreux.\r\n    Recouvrable par peinture alkyde diluable au White Spirit.\r\n    Atmosphères : rurale, urbaine, non corrosive.\r\n\r\n', 'Aspect satin velouté.\r\nBonne propriété anticorrosion.\r\nRecouvrable par peinture alkyde diluable au White Spirit.\r\nExcellentes propriétés mécaniques (dureté, adhérence...).\r\nBrillance à 60° : 10 U.B', '\r\n\r\nDensité : 1.45\r\nRendement :  8 m2/L sous 40μm\r\nBase : BLANC - INCOLORE - ROUGE BRUN - GRIS CLAIR\r\nConditionnement : 3L, 20Kg\r\n\r\n', 83),
(234, 'Appret 3250 XS ', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/primaire-anticorrosion/appret-3250/appret-3250-xs-510x559.png', '\r\nExtérieur.\r\nMétaux ferreux.\r\nRecouvrable par toute peinture (sauf époxy).\r\nAtmosphères : rurale, urbaine, non corrosive.\r\nIndétrempable.\r\n\r\n', '\r\n\r\n    Aspect mat, séchage rapide.\r\n    Bonne propriété anticorrosion (riche en pigment anticorrosion).\r\n    Temps de recouvrement très rapide.\r\n    Excellentes propriétés mécaniques (dureté, adhérence...).\r\n    Excellent pouvoir couvrant.\r\n\r\n', '\r\n\r\nDensité : 1.40\r\nRendement : 8 m2/L sous 40μm\r\nBase : BLANC - INCOLORE - ROUGE BRUN - GRIS CLAIR\r\nConditionnement : 3L, 20Kg\r\n\r\n', 76),
(235, 'Fixofer ', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/alkyde-monocomposant/fixofer/innova-fixofer-render-05-510x548.png', 'BRILLANT ET SATIN \r\nIntérieur/Extérieur.\r\nTravaux neufs et de rénovation.\r\nDirectement en multi-couches sur métaux ferreux nus ou en finition sur notre FIXOFER PRIMAIRE', 'Aspect brillant Existe en finition satinée.Séchage rapide.Bonne protection antirouille.\r\nBon pouvoir couvrant et garnissant.Existe en noir brillant et en noir mat.Rendement élevé\r\nApplication et entretien facile', 'Densité : 1.32\r\nRendement : 10 - 12 m2/L\r\nBase : BLANC - INCOLORE - NOIR - NOIR MAT\r\nConditionnement : 0.75L, 3L, 15L\r\n\r\n', 41),
(260, 'Fixofer aqua ', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/alkyde-monocomposant/fixofer-aqua/fixofer_aqua-510x607.png', 'Intérieur / Extérieur Travaux neufs et de rénovation Pour la protection et la décoration des métaux ferreux Particulièrement adapté à l’entretient des ferroneries grilles portails clôtures tous supports ferreux usuels du bâtiment ', 'Aspect demi-brillant.\r\nSéchage rapide.\r\nBonne protection antirouille.\r\nBon pouvoir couvrant et garnissant.\r\nRendement élevé.\r\nApplication et entretien faciles', '\r\n\r\nDensité : 1.35\r\nRendement : 10 - 12 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 1L, 3L, 12L\r\n\r\n', 33),
(261, 'Laque 2000 - 2010 - 2020', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/alkyde-monocomposant/laque-2000-2100-2020/laque-2000-510x559.png', 'BRILLANT (2000) / SATIN (2010) / MAT (2020)Intérieur/Extérieur Travaux neufs et de rénovation Directement en multi-couches sur métaux ferreux nus ou en finition sur notre FIXOFER PRIMAIRE en environnement difficile\r\n\r\n', 'Aspect brillant tendu.\r\nSéchage rapide.\r\nFaible odeur.\r\nExcellent tendu.\r\nExcellent pouvoir couvrant, rendement élevé.\r\nFacilité d’application et d’entretien (lessivable)', '\r\n\r\nDensité :  1.29\r\nRendement :  12 - 14 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 0.75L, 3L, 15L, 15.05L\r\n\r\n', 32),
(262, 'Laque 7037 XS ', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/alkyde-monocomposant/laque-7037/laque-7037-xs-510x559.png', 'Extérieur.\r\nMétaux ferreux bruts ou recouverts d’une ancienne peinture adhérente.\r\nAtmosphère rurale, urbaine, non corrosive.\r\nSéchage rapide', 'Aspect brillant tendu.\r\nSéchage très rapide permettant une manipulation en moins d’une heure.\r\nBonne stabilité de teinte et de brillant aux intempéries.\r\nSystème anticorrosion avec notre APPRET 3250', '\r\n\r\nDensité : 1.26\r\nRendement : 12 - 14m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 0.75L, 3L, 15L\r\n\r\n', 40),
(263, 'Laque 1850 martelé XS ', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/alkyde-monocomposant/laque-1850-martele/laque-1850-xs-510x701.png', 'Extérieur/Intérieur.\r\nMétaux ferreux bruts.\r\nAtmosphères : rurale, urbaine, non corrosive.\r\nPour pièces devant résister à de la moyenne température', 'Aspect semi brillant, effet aluminium martelé.\r\nSéchage rapide.\r\nBonne résistance anticorrosion.\r\nBonne résistance à la température, jusqu’à 150°C', '\r\n\r\nDensité : 0.96\r\nRendement : 10 - 12 m2/L\r\nBase : GRIS ALUMINIUM\r\nConditionnement : 0.75L, 3L, 15.05L\r\n\r\n', 46),
(264, 'Laque 1880 alu XS ', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/alkyde-monocomposant/laque-1880-alu/laque-1880-alu-510x559.png', 'Extérieur/Intérieur.\r\nMétaux ferreux brut uniquement destinés à monter en température', 'Aspect brillant, effet aluminium.\r\nHaute résistance à la température : 250°C en permanent, 300°C en température maximale.\r\nBonne résistance anticorrosion', '\r\n\r\nDensité : 0.94\r\nRendement : 10 - 12 m2/L\r\nBase : GRIS ALUMINIUM\r\nConditionnement : 0.75L, 3L, 15.05L\r\n\r\n', 48),
(265, 'Appret 3480 2K ', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/systeme-epoxy-bi-composant/appret-3480/appret-3480-2k-510x701.png', 'Intérieur/Extérieur.Métaux ferreux et non ferreux, bétons et dérivés.Résistance chimique et protection anticorrosion élevées en environnement atmosphérique agressif : zones industrielles et maritimes exposées, industrie chimique', 'Excellente adhérence sur différents supports.Excellente protection anticorrosionExcellente  Applicable en forte épaisseur (80-100m sec la couche).Recouvrable par laque époxy ou laque polyuréthane.Séchage et recouvrement rapides.\r\n\r\n', '\r\n\r\nDensité : 1.42\r\nRendement : 4 m²/Kg sous 80-100μm - 7-8 m2/Kg sous 40μm\r\nBase : BLANC\r\nConditionnement : 3L, 20Kg\r\n\r\n', 49),
(298, 'Laque 1440 2K ', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/systeme-epoxy-bi-composant/laque-1440/laque-1440-2k-510x701.png', 'Intérieur/Extérieur.\r\nMétaux ferreux et non ferreux, bétons et dérivés.\r\nRésistance chimique et protection anticorrosion élevées en environnement atmosphérique agressif : zones industrielles et maritimes exposées, industrie chimique...\r\n', 'Excellente adhérence sur différents supports.\r\nExcellente résistance chimique.\r\nExcellente résistance à l’abrasion.\r\nBon pouvoir couvrant.\r\nFinition du système anticorrosion époxydique, forte épaisseur.\r\nBonne résistance à l’essence', '\r\n\r\nDensité : 1.58\r\nRendement : 8 - 9 m2/L sous 40μm\r\nBase : BLANC - INCOLORE\r\nConditionnement : 3L, 15.05L\r\n\r\n', 54),
(299, 'Appret 3700 2K', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/systeme-pu-bi-composant/appret-3700/appret-3700-2k-2-510x701.png', 'Extérieur/Intérieur.Métaux ferreux et non ferreux, métaux revêtus en bon état, bardage pré laqué, bétons et dérivés, plastique rigide, polyester, aluminium Environnement industriel, ambiance maritime exposée, bateau.\r\n\r\n', 'Aspect mat velouté Excellente adhérence même sur support difficile.\r\nExcellent tendu.Bonne tenue aux produits chimiques, graisses, huiles, solvants, acides et bases.Sous-couche du système anticorrosion polyuréthane', '\r\n\r\nDensité : 1.45\r\nRendement : 8 - 10 m2/L sous 40 µm\r\nBase :  BLANC\r\nConditionnement :  0.75L, 3L, 15.05L\r\n\r\n', 56),
(300, 'Laque PU 2K (1310 - 1320 - 1380) ', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/systeme-pu-bi-composant/laque-1310-1320-1380/laque-1380-2k-510x701.png', 'BRILLANT (1380), SATIN (1310), MAT (1320) Extérieur/Intérieur Métaux ferreux et non ferreux, métaux revêtus en bon état, bardages pré laqués bétons et dérivés, plastique rigide, polyester, aluminium Environnement industriel ambiance maritime exposée', 'Aspect tendu.Excellente adhérence sur support difficile.Bonne dureté, résistant aux chocs et à l’usure.Bonne résistance chimique. Lessivabilité excellente.\r\nLessivabilité excellente.Excellente résistance aux U.V.', '\r\n\r\nDensité : 1.30\r\nRendement : 14 - 16 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement :  0.75L, 3L, 15.05L\r\n\r\n', 57),
(301, 'Laque 1351 2K ', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/systeme-pu-bi-composant/laque-1351/laque-1351-2k-510x701.png', '\r\n\r\n    Extérieur/Intérieur.\r\n    Métaux ferreux et non ferreux, métaux revêtus en bon état\r\n    Environnement industriel, ambiance maritime exposée, ambiance corrosive.\r\n\r\n', 'Aspect brillant tendu.Laque polyuréthane haute de gamme à haut brillant.Très grande  dureté, résistance accrue aux rayures.Excellente résistance aux U.V. longévité des teintes Bonne tenue aux produits chimiques graisses huiles solvants\r\n\r\n', '\r\n\r\nDensité : 1.35\r\nRendement : 14 - 16 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 0.75L, 3L, 15.05L\r\n\r\n', 60),
(302, 'Novathane aqua 2K ', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/systeme-pu-bi-composant/novathane-aqua-2k/novathane_aqua_2k-510x701.png', '\r\n\r\n    Intérieur / Extérieur\r\n    Travaux neufs et de rénovation.\r\n    Décoration et protection des murs et sols.\r\n    Bois et dérivés, bétons et dérivés, parquets bois, faïence, plastique, polyester...\r\n\r\n', 'Aspect tendu. finition satinée.Bonne résistance à l’abrasion et à la rayure.\r\nExcellente résistance aux U.V.Bonne résistance chimique.Adhérence exceptionnelle en direct sur tous supports', '\r\n\r\nDensité :  1.40\r\nRendement : 12 - 14 m2/L\r\nBase : BLANC - INCOLORE\r\nConditionnement : 1L, 3L, 12L\r\n\r\n', 42),
(303, 'Appret 3520 ', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/systeme-caoutchouc-chlore/appret-352/appret-3520-xs-510x559.png\r\n    \r\n', '    Extérieur.\r\n    Métaux ferreux.\r\n    Bétons et dérivés.\r\n    Pour ambiance chimique agressive, maritime ou industrielle.\r\n    Revêtement de surfaces immergées : piscine, réservoirs d’eau non potable.\r\n', 'Aspect satin velouté.Bonne résistance aux acides et aux bases.Excellente résistance aux chlores.Bonne résistance aux produits chimiques.Ne résiste pas aux solvants.Riche en pigments anticorrosion.Système anticorrosion avec en finition notre LAQUE 1540', '\r\n\r\nDensité : 1.32\r\nRendement :  8- 10 m2/L\r\nBase :  GRIS - ROUGE BRUN\r\nConditionnement :  3L, 15L\r\n\r\n', 44),
(304, 'Laque 1540 ', 'https://www.peintures-innova.fr/thumbs/peintures/metaux/systeme-caoutchouc-chlore/laque-1540/laque-1540-510x559.png', '\r\n    Métaux ferreux.\r\n    Bétons et dérivés.\r\n    Pour ambiance chimique agressive, maritime ou industrielle.\r\n    Revêtement de surfaces immergées : piscines, réservoirs d’eau non potable...\r\n', 'Aspect brillant.Bonne résistance aux acides et aux bases.Excellente résistance aux chlores.Bonne résistance aux produits chimiques.Ne résiste pas aux solvants.Système anticorrosion avec APPRET 3520.Insaponifiable : application possible sur fonds alcalins', '\r\n\r\nDensité : BLANC - INCOLORE - ROUGE BRUN\r\nRendement :1.37\r\nBase : 8 - 10 m2/L\r\nConditionnement : 0.75L, 3L, 15L\r\n\r\n', 65);

-- --------------------------------------------------------

--
-- Structure de la table `reservation`
--

CREATE TABLE `reservation` (
  `id` int(11) NOT NULL,
  `paints_id` int(11) NOT NULL,
  `users_id` int(11) NOT NULL,
  `created_at` datetime NOT NULL COMMENT '(DC2Type:datetime_immutable)'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Structure de la table `sub_category`
--

CREATE TABLE `sub_category` (
  `id` int(11) NOT NULL,
  `category_id` int(11) NOT NULL,
  `name` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `sub_category`
--

INSERT INTO `sub_category` (`id`, `category_id`, `name`) VALUES
(14, 9, 'Finition Brillante'),
(15, 9, 'Finition satinée'),
(16, 9, 'Finition soie'),
(17, 9, 'Finitions velours'),
(18, 9, 'Finitions mate'),
(19, 10, 'Enduits décoratifs'),
(20, 10, 'Peinture dépolluante'),
(21, 11, 'Impression fixateur'),
(22, 11, 'Film mince D2'),
(23, 11, 'Peinture minérale/organo-minérale'),
(24, 11, 'Revêtement Semi Epais R.S.E D3'),
(25, 11, 'Revêtement d\'imperméabilité 11-12-13-14'),
(26, 11, 'Revêtement plastique épais R.P.E'),
(27, 11, 'Lasure béton'),
(28, 11, 'Toiture'),
(29, 11, 'Hydrofuge/Antimousse'),
(30, 12, 'Impression/Saturateur'),
(31, 12, 'Peinture micropeuse de finition'),
(32, 12, 'Lasure'),
(33, 12, 'Vernis'),
(34, 13, 'Domestique'),
(35, 13, 'Industriel'),
(36, 13, 'Parquet bois'),
(37, 13, 'Sol sportif'),
(38, 13, 'Piscine'),
(39, 14, 'Primaire Anticorrosion'),
(40, 14, 'Alkyde monocomposant'),
(41, 14, 'Systéme époxy 2K'),
(42, 14, 'Systéme PU 2K'),
(43, 14, 'Systéme caoutchouc-chloré'),
(44, 14, 'Diluants');

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `lastname` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `firstname` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `category`
--
ALTER TABLE `category`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `doctrine_migration_versions`
--
ALTER TABLE `doctrine_migration_versions`
  ADD PRIMARY KEY (`version`);

--
-- Index pour la table `messenger_messages`
--
ALTER TABLE `messenger_messages`
  ADD PRIMARY KEY (`id`),
  ADD KEY `IDX_75EA56E0FB7336F0` (`queue_name`),
  ADD KEY `IDX_75EA56E0E3BD61CE` (`available_at`),
  ADD KEY `IDX_75EA56E016BA31DB` (`delivered_at`);

--
-- Index pour la table `paints`
--
ALTER TABLE `paints`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `reservation`
--
ALTER TABLE `reservation`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `UNIQ_42C8495567B3B43D` (`users_id`),
  ADD KEY `IDX_42C84955CAE3451D` (`paints_id`);

--
-- Index pour la table `sub_category`
--
ALTER TABLE `sub_category`
  ADD PRIMARY KEY (`id`),
  ADD KEY `IDX_BCE3F79812469DE2` (`category_id`);

--
-- Index pour la table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `category`
--
ALTER TABLE `category`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;

--
-- AUTO_INCREMENT pour la table `messenger_messages`
--
ALTER TABLE `messenger_messages`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table `paints`
--
ALTER TABLE `paints`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=305;

--
-- AUTO_INCREMENT pour la table `reservation`
--
ALTER TABLE `reservation`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT pour la table `sub_category`
--
ALTER TABLE `sub_category`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=45;

--
-- AUTO_INCREMENT pour la table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `reservation`
--
ALTER TABLE `reservation`
  ADD CONSTRAINT `FK_42C8495567B3B43D` FOREIGN KEY (`users_id`) REFERENCES `users` (`id`),
  ADD CONSTRAINT `FK_42C84955CAE3451D` FOREIGN KEY (`paints_id`) REFERENCES `paints` (`id`);

--
-- Contraintes pour la table `sub_category`
--
ALTER TABLE `sub_category`
  ADD CONSTRAINT `FK_BCE3F79812469DE2` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
